# This workflow will perform a fast test

name: Angular Fast Test

on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install
      - run: npm run testgithub
